export const RepertorioService = {
  // ...existing code...
  getAll: async () => {
    // ...logic not implemented...
  },
  delete: async (id: string) => {
    // ...logic not implemented...
  },
  // ...existing code...
};
